services:
  backend:
    image: projectcsi401
    ports:
      - "9999:30100"
  frontend:
    image: ecmsfrontend
    ports:
      - "3000:30000"
    depends_on:
      backend:
        condition: service_started

